--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: java-app-ingress
  namespace: my-java-appp
spec: 
  rules: 
    - 
      host: kltf.co.uk
      http: 
        paths: 
          backend: 
            - 
              service: 
                name: java-app-svc
                port: 8080
