--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  annotations: 
    INGRESS.kubernetes.io/rewrite-target: /
  name: java-app-ingress
  namespace: springbootjavaapp
spec: 
  rules: 
    - 
      host: kltf.co.uk
      http: 
        paths: 
          - 
            backend: 
              service: 
                name: java-app-svc
                port: 
                  number: 80
            path: /
            pathType: Prefix
   
