apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: my-java-app
        image: 499199586988.dkr.ecr.ap-southeast-1.amazonaws.com/testpro@sha256:8a0e39b2cd75c6fd8b8b99fd3d4ab9634d2a93a82a8cb5a96bb405e54f7f9fef
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
# service type NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8085
  type: NodePort
